name: Release All
on: 
  workflow_dispatch:
  push:
    branches:
      - dev
      - master
      - experimental
      # - staged
    paths-ignore:
      - 'docs/**'
      # - ".github/**"
      - "howto/**"
      - "*.md"
      - ".clang-format"
jobs:
  build_macOS:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        qt_ver: [ 6.8.0 ]
        qt_arch: [clang_64]
    env:
      targetName: GoldenDict
      version: 24.11.0
      version-suffix: ${{ !contains(github.ref_name,'master') && 'alpha' || 'Release' }}
      prerelease: ${{ !contains(github.ref_name,'master') }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: install deps on macos
        run: |
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=TRUE
          brew install cmake ninja pkg-config create-dmg \
          opencc libzim hunspell xapian \
          libiconv libogg libvorbis \
          lzo bzip2 zstd lzip
          
          git clone https://github.com/xiaoyifang/eb.git
          cd eb && ./configure && make -j 8 && sudo make install && cd ..
                
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          modules: qtwebengine qtwebchannel qtpositioning qt5compat qtmultimedia qtimageformats qtspeech
          
      - name: compile
        run: |
          mkdir build_dir
          cmake -S . -B build_dir -G Ninja -DWITH_FFMPEG_PLAYER=OFF -DWITH_TTS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_OSX_DEPLOYMENT_TARGET="12.0"
          cmake --build build_dir
          
      - name: package
        run: |
          cmake --install build_dir/
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: '*.dmg'
  publish:
    needs: [build_macOS]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Print Items
        run: |
          ls

          sudo apt-get install tree

          tree

